### ISSUE TITLE
Fitting data with true histogram pdf does not yield perfect agreement

### ISSUE THREAD

**Issue by bgrube** [dglazier/brufit#34]
I modified the tutorial in [FitHSMCModel.C](https://github.com/dglazier/brufit/blob/R6.28/tutorials/sPlotEventsPDF/FitHSMCModel.C) such that the data that are used to create the template histogram pdf and the data that are fitted are identical (see [FitHSMCModel2.py](https://github.com/bgrube/brufit/blob/fitWithTrueTemplate/tutorials/sPlotEventsPDF/FitHSMCModel2.py)). Consequently, when fixing all fudge parameters to their nominal values, the fit result should match the data perfectly.
This works nicely, if I fit the signal pdf to the signal data: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/9638d568-220f-4eaa-88f6-4d8697ceac7d)
or the background pdf to the background data: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/34ba4d78-edeb-40d6-bca1-f8887b022b22)
To achieve the above I had to change a few things (see branch [fitWithTrueTemplate](https://github.com/bgrube/brufit/tree/fitWithTrueTemplate)):
* switch off averaging when plotting pdfs and increase precision when plotting pdfs (see a05a16ccb4b0a4e8bc8edc41d62e9c65841e10c8)
* disable the smoothing of the template histograms (see 75e17eb2c27e1ac55af05e69bf5b06381d5177d5)

However, when I fit the sum of signal and background pdfs to the corresponding true distribution, the fit result deviates from the data, although also in this case the pdf is in principle able to reproduce the data exactly: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/9a74a477-a512-4792-bc15-1c59ae123761)
The reason seems to be that the yields found by the fit are off by 45 counts, which corresponds to about 15% of the uncertainty.

Performing the same study for the data I use to measure the proton-track efficiency, the effect is even more pronounced: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/d9171ba7-427c-4fd3-ae65-e7e20e804eaa)

It is unclear to me why this happens and I'm unsure whether this may hint at a deeper problem. Any thoughts on how to debug this would be welcome.

**Comment by dglazier** [comment]
Thanks Boris, it is an interesting problem, I will try and look into it over the next few days.

**Comment by dglazier** [comment]
First off I just ran the exercise with my own code/branch. What I find is that to correctly fit the histograms it needs to have a free scale parameter (comes to 1.03). This is true of signal only fits and total data fits. But the resulting fits look fine to me. 
![SignalFixScale](https://github.com/dglazier/brufit/assets/6430973/462a920d-a86a-4c2d-ae18-b97856776a68)
![SignalFreeScale](https://github.com/dglazier/brufit/assets/6430973/a9b725ad-eb05-4aaa-8fe1-621c96ed0ed3)
![DataFixScale](https://github.com/dglazier/brufit/assets/6430973/6588d689-bbb1-4485-9623-d5be0d7ce025)
![DataFreeScale](https://github.com/dglazier/brufit/assets/6430973/5608f407-09d2-4677-85f1-1624cec18366)

I think this is a result of the smoothing, which must broaden the distribution a little.

**Comment by dglazier** [comment]
I have run your code and get the same results. It is not clear there is anything really wrong here, the deviation is very small and may just be due some minimzer setting like tolerance or step size, (which are not trivial to change it seems).
Is it posible to have the sample file you used for your proton track efficiency study where the effects are more pronounced ?

**Comment by bgrube** [comment]
Thank you very much, Derek, for looking into this!
It is indeed a subtle effect for the 100k events generated in the tutorial. However, if I increase the number of generated events to 10M the deviation becomes more pronounced:
![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/a1401608-fef9-46a5-87dc-91902f9adc97)
You can find the file from my proton study at `/w/halld-scshelf2101/bgrube/ProtonTrackEfficiency/ReactionEfficiency/data/MCbggen/2017_01-ver03_goodToF/pippippimpimpmiss_flatTree.MCbggen_2017_01-ver03_goodToF.root.brufit`:
* the tree name is `pippippimpimpmiss`
* the name of the fitted variable is `MissingMassSquared_Measured`
* the fit range is `[-0.25, 3.75]`
* the event-ID variable is `ComboID`
* signal events have `IsSignal == 1`, background events `IsSignal == 0`
I added an example script at https://github.com/bgrube/brufit/blob/fitWithTrueTemplate/tutorials/sPlotEventsPDF/FitHSMCModel3.py, which gives the following output:
![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/4173f7eb-be9e-4243-ab20-dc338a8de557)
This is different from the plot above because I left off the RF side-band subtraction, which is an irrelevant detail here.

**Comment by bgrube** [comment]
As you pointed out, enabling the smoothing of the template histograms and correcting the inevitable broadening of these distributions by freeing the scale parameter seems to circumvent the issue. This is supported by the pulls for the signal and background yields: If I enable smoothing and fix the scale parameter to 1, the yields are biased:
![pulls_Yld_Signal](https://github.com/dglazier/brufit/assets/8039793/3ab407e0-4d95-44e7-9cce-d902a4fdd990)
![pulls_Yld_BG](https://github.com/dglazier/brufit/assets/8039793/166d7251-65bc-40f5-9415-3eb505057b10)
If I free the scale parameter, the bias vanishes:
![pulls_Yld_Signal](https://github.com/dglazier/brufit/assets/8039793/925a9491-35e7-418c-bed3-9665948ca366)
![pulls_Yld_BG](https://github.com/dglazier/brufit/assets/8039793/6531a324-e998-46ff-9020-ffddd7d8573d)

**Comment by dglazier** [comment]
I think one factor (possibly the main factor) is the finite uncertainty on the normalisation integral. The algorithm by default just calculates the intensity for the PDF at 5000 points and sums to get the integral. If I change to 100 or 50k bins then the effect gets worse then better. Using 10M events
100 points Norm Int
![NormInt100bin10M](https://github.com/dglazier/brufit/assets/6430973/2de33a86-634f-4fbe-a5c9-c23c68e383ae)

50k points Norm Int
![NormInt50kbin10M](https://github.com/dglazier/brufit/assets/6430973/bd9dd259-c2de-424a-b163-cfb3c58ca4e3)

Although the 50k points does not seem to be significantly better than 5000.

**Comment by dglazier** [comment]
Also if I go back to my default method with fudge parameters and smoothing. The results look like what I would want if fitting an independent data set, so I think the method is OK for fitting data independent of the simulated data

![NormInt50kbin10MParsSmooth](https://github.com/dglazier/brufit/assets/6430973/f1c3053e-2e26-452f-a1e3-af0f15cc2419)

I will look at your data next.

**Comment by bgrube** [comment]
Thanks a lot, Derek! I tried 50k integration points for the proton-efficiency sample and also here the result changes only a tiny bit: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/47d686fd-d411-4624-89ff-be34977f09db)

**Comment by bgrube** [comment]
I also tried to fit the proton-efficiency data with smoothing enabled and freed scale parameters for both signal and background PDFs. Unfortunately, in this case already fitting the signal distribution with the signal PDF does not work well: ![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/a63c0455-4e96-4dc5-a1aa-18788f5050eb)
Same goes for fitting the background distributions with the background PDF:![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/cc4d012e-cd33-4c9c-84e9-18f4b311a4cc)
The fit of the total distribution fails because the scale parameter for the signal hits the parameter limit:![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/c1f509a0-84a0-47ce-afda-0c5f26188dda)

**Comment by dglazier** [comment]
Hi Boris,
  For your proton test data you made the comment "This is different from the plot above because I left off the RF side-band subtraction, which is an irrelevant detail here."
  Does that mean the dataset includes RF background, or did you remove  these as well as the weights ? If the RF background has not been removed then the pulls cannot be OK by construction. Also does the background sample also have an RF background sample that should be subtracted ?  I note the yields and shapes look quite different in your more recent plots than the original in your first message.

EDIT : no actually the pulls should probably be OK even without weights in this case. I think the problem may lie in the similarity of the two shapes, leading to strong correlations.

Cheers
Derek

**Comment by dglazier** [comment]
OK, so I think I get the problem, it is the interpolation of the histogram. If I turn off interpolation it looks like the simple example case.
![DataFixNoIterp](https://github.com/dglazier/brufit/assets/6430973/140a2c16-b7c7-4993-8cbb-3e9ad13ae7a3)

In evaluate    and EvaluateMC   return  fHist->weight(RooArgSet(*fx_off,*falpha),0,kFALSE); //changed from 1 to 0
 
I need to think a bit more as to what the best strategy is here. One thing that is straightforward is just to increase the bins of the 1D template, so the interpolation is less of an effect . Unfortunately this does not seem to work from the script at the moment, somehow it gets overwritten in the PDF copy (I will fix this). But if you want to try you can just edit the source code and hardwire it .,
Int_t NBins0=500; //in constructor of RooHSEventsHistPDF

Cheers
Derek

**Comment by bgrube** [comment]
Great, this looks good! I'll give it a try.

Concerning your previous post: Sorry for being unspecific about the simulated data sample. It consist of a cocktail of various reactions. One of these reactions is the signal reaction, the others constitute the background sample. For all reactions, the simulation generates off-time events that in the real analysis are removed using side-band subtraction. Leaving off the RF-sideband subtraction slightly changes the shapes of the signal and the background distributions and increases the number of events in both samples. Still, the individual signal and background distributions are fitted well by the corresponding PDFs:![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/99639075-f95f-40ae-88e1-932af2b6eef7)
![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/95706a04-1cb6-42af-86cb-69938a7ebad5)
However, as shown in https://github.com/dglazier/brufit/issues/34#issuecomment-1996042873, the fitter could not match well the sum of the two PDFs to the total data sample, although it should have been be able to do so.

**Comment by bgrube** [comment]
Changing https://github.com/bgrube/brufit/blob/27fa9d86eab79da2ebb268d0f83c32f1d5b57e19/core/RooHSEventsHistPDF.cpp#L54 to `Int_t NBins0=1000;` goes in the right direction:![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/d4698be0-eb78-46cd-a267-a55389e4ef9a)
The deviation of the yield estimates from the true values (signal yield = 2901902, background yield = 6711205) reduces drastically from more than 10 times the uncertainty estimate to 10% of the uncertainty estimate. 

Increasing the number of bins even further to 10000 reduces the deviation to about 5%:![ResultsHSMinuit2](https://github.com/dglazier/brufit/assets/8039793/a7231b26-063d-407f-b8e1-4eed52695c38)
However, in both cases the plotting of the pulls seems to be broken.

**Comment by dglazier** [comment]
The pulls are understandable, if there are 100 PDF bins for every plotting bin then it will essentially give a random fluctuation around the plotting value with sigma = sqrt(Npdf) which will be 10x larger (100x bins) than sigma = sqrt(Nplot) for the data.

I am actually wondering why we do an event-by-event fit here. It sounds like what you want is a binned fit with bins matched between PDF and data ? At least in the case of sharp peaking and high statistics.

I plan to try adding an adaptive binning algorithm to help with sharp structures and will try getting the binned fits running.

**Comment by dglazier** [comment]
So here is a plot with an adaptive binning scheme. Green is histogram with 100 bins, blue 2000 bins and red adaptive with 139 bins and smoothing.

![AdaptLog](https://github.com/dglazier/brufit/assets/6430973/51ef6b28-4376-4589-a20b-ae5bb0e4ffd0)
![AdaptZoom](https://github.com/dglazier/brufit/assets/6430973/7756bb8c-4e6e-4e59-991f-d64a04a10590)

I will make a new EventsHistPeak class and see if it improves things. I think the problem with just using lots of bins (other than performance) is it may "over-train" on the simulated data, but this might not be a real problem in practise.

**Comment by dglazier** [comment]
Also here is a fit plot with 5000 bins, no interpolation and smoothing. It gets pretty close.
![Bins5000NoInterpSmooth](https://github.com/dglazier/brufit/assets/6430973/c10f4e9d-3a5a-476b-9023-53101d7218ec)

**Comment by bgrube** [comment]
Great! Thanks a lot, Derek! This looks good. I agree that fitting the template histograms to binned data should work as well. Do you have the code in a branch so that I can give it a try?

**Comment by dglazier** [comment]
small update, fits with same class (not adaptive) with no interpolation or smearing, 100 bins and 500k integration samples gets pretty much right on
![NoInterp500kInt](https://github.com/dglazier/brufit/assets/6430973/1a070f1a-9315-4c8d-bcb8-a358254ff146)

**Comment by bgrube** [comment]
Nice! Thank you very much, Derek! Please let me know when you have a branch that I could try out.

**Comment by dglazier** [comment]
Apologies for the delay with the new branch. Things are working well with the template fitting but I wanted to make sure it worked with the Toy generator so we can really test the best methods. This is taking a little longer, hopefully done by tomorrow.

**Comment by bgrube** [comment]
No need to apologize, Derek. I'm very grateful that you work on this!

**Comment by dglazier** [comment]
I made a new branch on my github called peakhist
I attach some test scripts based on your proton efficiency data.
Let me know if anything is unclear. There is a brief README
[test_files.tar.gz](https://github.com/dglazier/brufit/files/14746387/test_files.tar.gz)

To summarise, the fits now work as you had hoped when fitting a template histogram to the data which it is created from. If you use different data, the fit does not work so well. The new BruEventsHistPeakPDF seems to give better results if you do event-by-event fitting.
I added in binned fitting which you can set with 
 FitManager RF;
  RF.DoBinnedFits();//not event-by-event
...
  RF.SetUp().GetVar("MissingMassSquared_Measured")->setBins(500);  //binned fit with 500 bins

Cheers
Derek

**Comment by bgrube** [comment]
Thank you so much, Derek! I'll give it a try.

**Comment by bgrube** [comment]
Sorry for leaving this open so long. Your changes fixed the issue, so I'm closing it. Many thanks for your efforts, Derek!
